# Generated by Django 4.2.23 on 2025-07-07 05:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("channel_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("thumbnail", models.URLField()),
                ("description", models.CharField(max_length=500)),
                (
                    "subscriber_count",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "video_count",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "views_count",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("view_count", models.BigIntegerField()),
                ("like_count", models.BigIntegerField()),
                ("comment_count", models.IntegerField()),
                ("publish_time", models.DateTimeField()),
                ("is_shorts", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtubeapp.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=20)),
                ("publish_time", models.DateTimeField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtubeapp.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_link", models.URLField()),
                ("external_link", models.URLField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtubeapp.channel",
                    ),
                ),
            ],
        ),
    ]
